/*******************************************************************************
* Copyright (C) 2016 Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com> - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 07:48:42 AM UTC 
//


package com.quakearts.tools.web.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" type="{http://quakearts.com/scaffolding}scaffolding-properties" minOccurs="0" maxOccurs="1"/>
 *         &lt;element name="template-group" type="{http://quakearts.com/scaffolding}page" minOccurs="0" maxOccurs="unbounded"/>
 *         &lt;element name="resource" type="{http://quakearts.com/scaffolding}resource" minOccurs="0" maxOccurs="unbounded"/>
 *         &lt;element name="folder-structure" type="{http://quakearts.com/scaffolding}folder-structure"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties",
    "templateGroups",
    "resources",
    "folderStructure"
})
@XmlRootElement(name = "scaffolding", namespace = "http://quakearts.com/scaffolding")
public class Scaffolding {

    @XmlElement(namespace = "http://quakearts.com/scaffolding")
    protected ScaffoldingProperties properties;
    @XmlElement(namespace = "http://quakearts.com/scaffolding", required = true, name="template-group")
    protected List<TemplateGroup> templateGroups;
    @XmlElement(namespace = "http://quakearts.com/scaffolding", required = true, name="resource")
    protected List<Resource> resources;
    @XmlElement(name = "folder-structure", namespace = "http://quakearts.com/scaffolding", required = true)
    protected FolderStructure folderStructure;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link ScaffoldingProperties }
     *     
     */
    public ScaffoldingProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScaffoldingProperties }
     *     
     */
    public void setProperties(ScaffoldingProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateGroup }
     * 
     * 
     */
    public List<TemplateGroup> getTemplateGroups() {
        if (templateGroups == null) {
            templateGroups = new ArrayList<TemplateGroup>();
        }
		return templateGroups;
	}
    /**
     * Gets the value of the resource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Resource }
     * 
     * 
     */
    public List<Resource> getResources() {
        if (resources == null) {
            resources = new ArrayList<Resource>();
        }
		return resources;
	}

    /**
     * Gets the value of the folderStructure property.
     * 
     * @return
     *     possible object is
     *     {@link FolderStructure }
     *     
     */
    public FolderStructure getFolderStructure() {
        return folderStructure;
    }

    /**
     * Sets the value of the folderStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderStructure }
     *     
     */
    public void setFolderStructure(FolderStructure value) {
        this.folderStructure = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public int getTotalUnits(){
    	int totalUnits = 0;
    	for(TemplateGroup templateGroup:getTemplateGroups()){
    		totalUnits+=templateGroup.getTemplates().size();
    	}
    	
    	totalUnits+= getResources().size();
    	totalUnits+= folderStructure!=null && folderStructure.folder!=null?folderStructure.folder.getFolderCount():0;
    	
    	return totalUnits;
    }
}
