/*******************************************************************************
 * Copyright (C) 2017 Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com> - initial API and implementation
 ******************************************************************************/
package com.quakearts.test.hibernate;
// Generated Sep 30, 2015 12:15:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Guests generated by hbm2java
 */
public class Guests implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5755033236365062992L;
	private String id;
	private String name;
	private boolean valid;
	private Set<Seating> seatings = new HashSet<Seating>(0);
	private Set<Party> parties = new HashSet<Party>(0);

	public Guests() {
	}

	public Guests(String id, boolean valid) {
		this.id = id;
		this.valid = valid;
	}

	public Guests(String id, String name, boolean valid, Set<Seating> seatings, Set<Party> parties) {
		this.id = id;
		this.name = name;
		this.valid = valid;
		this.seatings = seatings;
		this.parties = parties;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public Set<Seating> getSeatings() {
		return this.seatings;
	}

	public void setSeatings(Set<Seating> seatings) {
		this.seatings = seatings;
	}

	public Set<Party> getParties() {
		return this.parties;
	}

	public void setParties(Set<Party> parties) {
		this.parties = parties;
	}

}
