package com.quakearts.test.hibernate;
// Generated Sep 30, 2015 12:15:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6985648196527733452L;
	private long id;
	private String itemName;
	private boolean valid;
	private Set<Party> parties = new HashSet<Party>(0);

	public Menu() {
	}

	public Menu(boolean valid) {
		this.valid = valid;
	}

	public Menu(String itemName, boolean valid, Set<Party> parties) {
		this.itemName = itemName;
		this.valid = valid;
		this.parties = parties;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public Set<Party> getParties() {
		return this.parties;
	}

	public void setParties(Set<Party> parties) {
		this.parties = parties;
	}

}
