/*******************************************************************************
* Copyright (C) 2016 Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com> - initial API and implementation
 ******************************************************************************/
package com.quakearts.test.hibernate;
// Generated Sep 30, 2015 12:15:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * Party generated by hbm2java
 */
public class Party implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4724154387939396474L;
	private long id;
	private Guests guests;
	private Seating seating;
	private Menu menu;
	private boolean valid;

	public Party() {
	}

	public Party(Guests guests, boolean valid) {
		this.guests = guests;
		this.valid = valid;
	}

	public Party(Guests guests, Seating seating, Menu menu, boolean valid) {
		this.guests = guests;
		this.seating = seating;
		this.menu = menu;
		this.valid = valid;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Guests getGuests() {
		return this.guests;
	}

	public void setGuests(Guests guests) {
		this.guests = guests;
	}

	public Seating getSeating() {
		return this.seating;
	}

	public void setSeating(Seating seating) {
		this.seating = seating;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

}
