package com.quakearts.test.hibernate;
// Generated Sep 30, 2015 12:15:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Seating generated by hbm2java
 */
public class Seating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8550798010244874438L;
	private long id;
	private Guests guests;
	private SeatingType seatingType;
	private boolean valid;
	private Set<Party> parties = new HashSet<Party>(0);

	public Seating() {
	}

	public Seating(boolean valid) {
		this.valid = valid;
	}

	public Seating(Guests guests, SeatingType seatingType, boolean valid, Set<Party> parties) {
		this.guests = guests;
		this.seatingType = seatingType;
		this.valid = valid;
		this.parties = parties;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Guests getGuests() {
		return this.guests;
	}

	public void setGuests(Guests guests) {
		this.guests = guests;
	}

	public SeatingType getSeatingType() {
		return this.seatingType;
	}

	public void setSeatingType(SeatingType seatingType) {
		this.seatingType = seatingType;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public Set<Party> getParties() {
		return this.parties;
	}

	public void setParties(Set<Party> parties) {
		this.parties = parties;
	}

}
